### ISSUE TITLE
Clicking 'cancel' in Print confirmation dialog causes blank screen with '0'

### ISSUE THREAD

**Issue by lauriek334** [BackPacker777/2020.NNSP-SignIn#13]
Using Firefox, the browser window is blanked and a 0 is displayed when the 'Cancel' button is clicked in the Print confirmation dialog
![image](https://user-images.githubusercontent.com/342894/151403810-0e1c9869-5f4b-42a7-b3d1-a7d5f1ff0e41.png)

**Comment by lauriek334** [comment]
This is a Firefox only issue so not a big deal right now.

**Comment by BackPacker777** [comment]
We only use Chrome, so.....
