### ISSUE TITLE
Clicking 'Yes' in the print confirmation dialog does not show the formatted print screen

### ISSUE THREAD

**Issue by lauriek334** [BackPacker777/2020.NNSP-SignIn#14]
Using Chrome Version 97.0.4692.99 (Official Build) (x86_64)
I added 2 patrollers to the roster
Clicked Print, entered "yes" in the Print confirmation dialog and clicked "OK"
The form reset but no print screen appeared. 
After checking, the days patrolled data was updated for each of the two patrollers entered.

**Comment by BackPacker777** [comment]
Do you have pop-ups blocked?

**Comment by lauriek334** [comment]
Had popups blocked. Now I have added the site to allow popups in chrome, I now see the formatted print screen.
![image](https://user-images.githubusercontent.com/342894/151409206-f50104af-b828-4e72-a9aa-7c32d46a8097.png)

**Comment by lauriek334** [comment]
Yes - I had popups blocked.  I’ve updated the issue on github and closed it.

Laurie Kirchmeier
***@***.***
