### ISSUE TITLE
Clicking SignIn on an already signed in entry and then clicking "Cancel" clears sone of the entry fields

### ISSUE THREAD

**Issue by lauriek334** [BackPacker777/2020.NNSP-SignIn#21]
Steps to reproduce:

1. Click on a "Sign In" button, enter a patroller id and radio and click "OK". The patroller details are filled out in the form
2. Click on the same "Sign In" button and then click the "Cancel" button in the modal entry form.  The existing patroller details are partially wiped out - the ID and the signoffs are still filled out but the name, rating are cleared.
If an entry is filled out and the "Sign On" button i clicked and then the modal entry dialog "cancelled" the original information in the entry should b preserved.

**Comment by BackPacker777** [comment]
I can't recreate the problem. Would you be able to do a little screen recording and email it to me? Thanks Laurie!

**Comment by lauriek334** [comment]
https://user-images.githubusercontent.com/342894/154969081-0cdc34e4-cb8c-4563-bad7-8c7db89d9261.mp4

Attached is a screen recording Howard. 
I think it might be better to change the "Sign In" button name (and color) to say "Edit" after a patroller has entered their details.  There may be a reason to go back and edit the radio # for instance OR to be able to remove their entry and re-add it say to another time slot in an evening shift OR another team for a weekend day shift.

**Comment by lauriek334** [comment]
IT looks like the localstorage has been somewhat cleared (but not completely after performing the above steps. Here's a screenshot.
![image](https://user-images.githubusercontent.com/342894/154970043-bbc32faf-cd80-453d-817f-6d12d7c20b35.png)

**Comment by BackPacker777** [comment]
Done.
